name: uninotes_mobile
description: Mobile Flutter version of UniNotes frontend
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  universal_html: ^2.2.4
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/